<?php $sum = 0; ?>
<?php echo $this->pageHeader('Cruscotto'); ?>
<div class="row">
    <?php
    echo $this->widgetText([
        'color'  => 'yellow',
        'col-lg' => $remainingDays ? 3 : 12,
        'col-md' => $remainingDays ? 6 : 12,
        'fa'     => 'eur',
        'label'  => 'Rimasti da spendere',
        'text'   => $this->currencyForma($monthBudget),
    ]);

    if ($remainingDays) {
        echo $this->widgetText([
            'color'  => 'primary',
            'col-lg' => 3,
            'col-md' => 6,
            'fa'     => 'calendar',
            'label'  => 'Giorni residui',
            'text'   => $remainingDays,
        ]);
        echo $this->widgetText([
            'color'  => 'green',
            'col-lg' => 3,
            'col-md' => 6,
            'fa'     => 'eur',
            'label'  => 'Rimasti al giorno',
            'text'   => $this->currencyForma($monthBudget / $remainingDays),
        ]);
        echo $this->widgetText([
            'color'  => 'green',
            'col-lg' => 3,
            'col-md' => 6,
            'fa'     => 'eur',
            'label'  => 'Rimasti al giorno da domani',
            'text'   => $remainingDays > 1 ? $this->currencyForma($monthBudget / ($remainingDays - 1)) : 'Non disponibile',
        ]);
    }
    ?>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Panoramica mensile spese</h4>
            </div>
            <div class="panel-body">
                <div id="monthly-overview" style="height:200px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Budget</h3>
            </div>
            <div class="panel-body">
                <?php if ($accounts): ?>
                    <table class="table">
                        <thead><tr><th>Descrizione</th><th class="text-right">Valore</th></tr></thead>
                        <tbody>
                            <?php foreach ($accounts as $account): ?>
                            <tr>
                                <td>
                                    <a href="<?php echo $this->url('accantonaMovement', ['action' => 'account', 'id' => $account['id']]); ?>"><?php echo $account['name']; ?></a>
                                </td>
                                <td class="text-right" style="min-width:130px;"><?php echo $this->currencyForma($account['total']); ?></td>
                            </tr>
                            <?php endforeach; ?>
                            <?php if ($this->userData()->hasStored()): ?>
                            <tr>
                                <td><a href="<?php echo $this->url('accantona_accantonato'); ?>">Accantonati</a></td>
                                <td class="text-right">
                                    <?php if ($stored > 0): ?>
                                        <?php echo '- ' . $this->currencyForma($stored); ?>
                                    <?php else: ?>
                                        <em>Non disponibile</em> <?php echo $this->helpTooltip('L\'accantonamento è una quota che viene destinata a coprire le spese.'); ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <div class="alert alert-warning" role="alert">
                        <p>
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            Non hai ipostato alcun conto nel riepilogo.
                        </p>
                        <p>
                            Impostando i conti nel riepilogo (es. Contanti, Conto corrente, ecc.) ti verranno suggeriti i budget giornalieri e il residuo spendibile fino
                            al prossimo stipendio.
                        </p>
                        <p>
                            Clicca <a href="<?php echo $this->url('accantonaAccount'); ?>">qui</a> per crearne o impostarne uno.
                        </p>
                    </div>
                <?php endif; ?>
                <div id="donut-accounts"></div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Spese per categoria</h3>
            </div>
            <div class="panel-body">
                <?php if ($avgPerCategory): ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Categoria</th>
                        <th class="text-right">Spesa media mensile</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($avgPerCategory as $row) : ?>
                        <?php if ($row['status'] == \Application\Entity\Category::STATUS_ACTIVE): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($row['description']); ?></td>
                            <td class="text-right">
                                <?php
                                if ($row['average'] <= 0) {
                                    $average = abs($row['average']);
                                    $sum += $average;
                                    echo $this->currencyForma($average);
                                }
                                ?>
                            </td>
                        </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td><strong>Somma</strong></td>
                        <td class="text-right"><strong><?php echo $this->currencyForma($sum); ?></strong></td>
                    </tr>
                    </tfoot>
                </table>
                <?php else: ?>
                    <div class="alert alert-danger" role="alert">
                        <p>
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            Non è stata definita alcuna categoria di spesa.
                        </p>
                        <p>
                            Le categorie di spesa ti aiutano monitorare le voci di spesa per te più significative
                            (es.&nbsp;Casa, Auto, Gas, ecc.).
                        </p>
                        <p>
                            Clicca <a href="<?php echo $this->url('accantona_categoria', array('action' => 'add')); ?>">qui</a> per crearne una.
                        </p>
                    </div>
                <?php endif; ?>
                <div id="donut-spends"></div>
            </div>
        </div>
    </div>
</div>
<?php $this->inlineScript()->captureStart(); ?>
Morris.Bar({
    data: <?php echo json_encode(array_map(function ($item) {
        return ['date' => $item['date'], 'amount' => abs($item['amount'])];
    }, array_values($monthlyOverviewData))); ?>,
    element: 'monthly-overview',
    hideHover: "auto",
    labels: ['Importo'],
    xkey: 'date',
    ykeys: ['amount'],
    resize: true,
    "yLabelFormat": function formatMoney(n) {
        var c = isNaN(c = Math.abs(c)) ? 2 : c,
          d = ',',
          t = '.',
          s = n < 0 ? '-' : '',
          i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))),
          j = (j = i.length) > 3 ? j % 3 : 0;

        return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
    }
});
<?php $this->inlineScript()->captureEnd(); ?>

<?php
if ($this->donutSpends) {
    $this->morris()->donut('donut-spends', $this->donutSpends);
}
if ($this->donutAccounts) {
    $this->morris()->donut('donut-accounts', $this->donutAccounts);
}
