<?php
/**
 * @var Laminas\Form\Form $form
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var string $error
 * @var string $message
 */
echo $this->pageHeader('Utente');
?>
<div class="row">
    <div class="col-lg-4 col-md-3">
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Cambio password
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->form()->openTag($form); ?>
                            <?php echo $this->sbaFormRow($form->get('current')); ?>
                            <?php echo $this->sbaFormRow($form->get('password')); ?>
                            <?php echo $this->sbaFormRow($form->get('password_confirm')); ?>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" type="submit">Salva</button>
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                        <?php if ($message): ?>
                        <div class="alert <?php echo $error ? 'alert-danger' : 'alert-success'; ?>">
                            <?php echo $message; ?>
                        </div>
                        <?php endif; ?>
                        <div class="form-group">
                            <a href="<?php echo $this->url('auth', ['action' => 'update']); ?>">Impostazioni utente</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-3">
    </div>
</div>
