<?php
/**
 * @var Auth\Form\AuthForm $form
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$form = $this->form;
$form->setAttributes(['action' => $this->url('auth', ['action' => 'login']), 'class' => 'form-signin']);
$form->prepare();
?>
<style type="text/css">
    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
</style>
<?php echo $this->form()->openTag($form); ?>
    <h1 class="form-signin-heading">Please sign in</h1>

    <?php echo $this->formLabel($form->get('email')); ?>
    <?php echo $this->formInput($form->get('email')); ?>

    <?php echo $this->formLabel($form->get('password')); ?>
    <?php echo $this->formInput($form->get('password')); ?>

    <!-- div class="checkbox">
        <?php echo $this->formRow($form->get('rememberme')->setAttribute('checked', 'checked')); ?>
    </div -->

    <div class="checkbox">
        <label><input name="rememberme" type="hidden" value="0"><input checked name="rememberme" type="checkbox" value="1">Remember Me</label>
    </div>

    <?php echo $this->formSubmit($form->get('submit')); ?>
    <br />
    <?php if ($this->messages): ?>
    <div class="alert alert-danger" role="alert"><?php echo $this->escapeHtml($this->messages); ?></div>
    <?php endif; ?>
    <div>
        <a href="<?php echo $this->url('auth_registration', ['action' => 'index']);?>"><?php echo $this->translate('Register'); ?></a>
        |
        <a href="<?php echo $this->url('auth_registration', ['action' => 'forgotten-password']);?>"><?php echo $this->translate('Forgotten Password'); ?></a>
    </div>

<?php echo $this->form()->closeTag(); ?>
