<?php
/**
 * @var Auth\Form\AuthForm $form
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var string $messages
 */
$this->headLink()->appendStylesheet('/css/page/user-login.css');
$form->setAttributes(['action' => $this->url('auth', ['action' => 'login']), 'class' => 'form-signin']);
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
    <img class="mb-4" src="/img/wallet.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
        <input name="email" type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
        <label for="floatingInput">Email address</label>
    </div>

    <div class="form-floating">
        <div class="form-floating">
            <input name="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
    </div>

    <div class="checkbox mb-3">
        <label>
            <input name="rememberMe" type="hidden" value="0">
            <input name="rememberMe" type="checkbox" value="1">
            Remember me
        </label>
    </div>

    <button class="w-100 btn btn-lg btn-primary" name="submit" type="submit">Sign in</button>

    <?php if ($messages): ?>
    <div class="m-1 text-danger" role="alert"><?php echo $this->escapeHtml($messages); ?></div>
    <?php endif; ?>
    <div class="mt-4">
        <a href="<?php echo $this->url('auth_registration', ['action' => 'index']);?>"><?php echo $this->translate('Register'); ?></a>
        |
        <a href="<?php echo $this->url('auth_registration', ['action' => 'forgotten-password']);?>"><?php echo $this->translate('Forgotten Password'); ?></a>
    </div>

<?php echo $this->form()->closeTag(); ?>
