<?php echo $this->pageHeader('Utente'); ?>
<div class="row">
    <div class="col-lg-4 col-md-3">
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Informazioni utente
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->form()->openTag($form); ?>
                            <div class="form-group">
                                <?php echo $this->sbaFormRow($form->get('name')->setAttribute('class', 'form-control')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->sbaFormRow($form->get('surname')->setAttribute('class', 'form-control')); ?>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary form-control" type="submit">Salva</button>
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                        <div class="form-group">
                            <!--<a href="javascript:void(0);">Cambia password</a>-->
                        </div>
                        <?php if ($message): ?>
                        <div class="alert alert-success">
                            <?php echo $message; ?>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-3">
    </div>
</div>