<?php
/* @var $this \Zend\View\View */
$this->form->setAttribute('action', $this->url('accantona_accantonato', array('action' => 'add')));
$this->form->prepare();
?>
<div class="row">
    <?php echo $this->pageHeader('Aggiungi accantonamento'); ?>
</div>
<?php echo $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-lg-6">
            <?php $element = $form->get('valuta'); ?>
            <?php $errors = $this->formElementErrors($element); ?>
            <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
                <?php echo $this->formLabel($element); ?>
                <?php echo $this->formInput($element); ?>
                <?php echo $errors; ?>
            </div>
    </div>
    <div class="col-lg-6">
        <?php $element = $form->get('importo'); ?>
        <?php $errors = $this->formElementErrors($element); ?>
        <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
            <?php echo $this->formLabel($element); ?>
            <?php echo $this->formInput($element); ?>
            <?php echo $errors; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php $element = $form->get('descrizione'); ?>
        <?php $errors = $this->formElementErrors($element); ?>
        <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
            <?php echo $this->formLabel($element); ?>
            <?php echo $this->formInput($element); ?>
            <?php echo $errors; ?>
        </div>

        <div class="text-right">
            <a class="btn btn-default" href="<?= $this->url('accantona_accantonato') ?>">Annulla</a>
            <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Salva</button>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
