<?php /* @var $this \Zend\View\View */ ?>
<?php echo $this->pageHeader('Aggiungi accantonamento'); ?>
<div class="row">
    <div class="col-lg-4">
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Aggiungi accantonamento
            </div>
            <div class="panel-body">
                <?php $this->form->setAttribute('action', $this->url('accantona_accantonato', array('action' => 'add')))->prepare(); ?>
                <?php echo $this->form()->openTag($this->form); ?>
                    <?php echo $this->sbaFormRow($form->get('valuta')); ?>
                    <?php echo $this->sbaFormRow($form->get('importo')); ?>
                    <?php echo $this->sbaFormRow($form->get('descrizione')); ?>
                    <div class="text-right">
                        <a class="btn btn-default" href="<?= $this->url('accantona_accantonato') ?>">Annulla</a>
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Salva</button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
    </div>
</div>
