<?php
/**
 * @var $this Zend\View\Renderer\PhpRenderer
 */
$title = 'Accantonati';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form action="<?php echo $this->url('accantona_accantonato', array('action' => 'add')); ?>" method="post">
    <table class="table">
        <thead>
            <tr>
                <th class="id">Id</th>
                <th class="valuta">Valuta</th>
                <th class="amount">Amount</th>
                <th>Description</th>
                <th class="actions">&nbsp;</th>
            </tr>
            <tr id="search">
                <td></td>
                <td>
                    <select class="form-control" id="monthsFilter" name="monthsFilter">
                        <option value="0" <?php if ($months == 0) echo 'selected="selected"'; ?>>Tutte</option>
                        <option value="1" <?php if ($months == 1) echo 'selected="selected"'; ?>>Ultimo mese</option>
                        <option value="3" <?php if ($months == 3) echo 'selected="selected"'; ?>>Ultimi 3 mesi</option>
                        <option value="6" <?php if ($months == 6) echo 'selected="selected"'; ?>>Ultimi 6 mesi</option>
                        <option value="12" <?php if ($months == 12) echo 'selected="selected"'; ?>>Ultimo anno</option>
                    </select>
                </td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($rows as $row): ?>
            <tr>
                <td><?php echo $row->id; ?></td>
                <td><?php echo $this->dateForma($row->valuta); ?></td>
                <td class="text-right"><?php echo $this->currencyForma($row->importo); ?></td>
                <td><?php echo $row->descrizione; ?></td>
                <td>
                    <a href="<?php echo $this->url('accantona_spesa', array('action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-default" aria-label="Edit">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </a>
                    <a href="<?php echo $this->url('accantona_spesa', array('action' => 'delete', 'id' => $row->id)); ?>" class="btn btn-default" aria-label="Edit">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>

        <tfoot>
            <tr>
                <td></td>
                <td class="valuta"><input class="form-control" name="valuta" type="date" value="<?php echo date('Y-m-d'); ?>" /></td>
                <td class="text-right"><input class="form-control" name="importo" size="7" type="number" /></td>
                <td><input class="form-control" name="descrizione" /></td>
                <td class="actions">
                    <button id="save" type="submit" class="btn btn-default show-on-edit" aria-label="Add">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
                    </button>
                </td>
            </tr>
        </tfoot>
    </table>
</form>
<script type="text/javascript">
    $('#search select').change(function(){
        location.href = "<?php echo $this->url(null, array('action' => 'index')); ?>" + '&monthsFilter=' + $('#monthsFilter').val();
    });
</script>
