<?php
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 * @var \Accantona\Form\AccantonatoForm $form
 */
?>
<?php echo $this->pageHeader('Accantonati'); ?>
<div class="row" id="search">
    <?php
    echo $this->widgetText(['color' => 'primary', 'col-lg' => '6', 'fa' => 'eur', 'label' => 'Saldo', 'text' => $this->currencyForma($this->balance)]);
    echo $this->widgetSelect([
        'col-lg'    => '6',
        'color'     => 'green',
        'fa'        => 'filter',
        'id'        => 'monthsFilter',
        'label'     => 'Periodo',
        'name'      => 'monthsFilter',
        'options'   => [0 => 'Tutte', 1 => 'Ultimo mese', 3 => 'Ultimi 3 mesi', 6 => 'Ultimi 6 mesi', 12 => 'Ultimo anno'],
        'selected'  => $months,
    ]);
    ?>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Lista accantonamenti</div>
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="accantonati">
                    <thead>
                        <tr>
                            <th>Valuta</th>
                            <th>Importo</th>
                            <th>Descrizione</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($rows as $row): ?>
                        <tr>
                            <td><?php echo $this->dateForma($row->valuta); ?></td>
                            <td class="text-right"><?php echo $this->currencyForma($row->importo); ?></td>
                            <td><?php echo $row->descrizione; ?></td>
                            <td>
                                <a href="<?php echo $this->url('accantona_accantonato', array('action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-default" title="Modifica">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <span data-href="<?php echo $this->url('accantona_accantonato', array('action' => 'delete', 'id' => $row->id)); ?>" class="btn btn-default delete-item" title="Elimina">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </span>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#search select').change(function(){
        location.href = "<?php echo $this->url(null, array('action' => 'index')); ?>" + '?monthsFilter=' + $('#monthsFilter').val();
    });

    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare l\'accantonamento selezionato?</h3>' +
            '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Importo</dt><dd>'  + button.parents('tr').find('.amount').html() + '</dd>' +
            '<dt>Data</dt><dd>'  + button.parents('tr').find('.date').html() + '</dd>' +
            '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });
    $(document).ready(function(){
        $('#accantonati').DataTable({
            "columnDefs": [
                {"targets": 0, "type": 'date-eu'},      //data
                {"targets": 1, "type": 'currency-it'},  //importo
                {"orderable": false, "targets": -1}     //azioni
            ],
            "language":{
                "url": "/vendor/datatables-plugins/i18n/Italian.json"
            },
            "order": [
                [0, "desc"]
            ],
            "responsive": true
        });
    });
</script>
<?php
$this->floatingButtons()->addAnchorItem(array(
    'href'  => $this->url('accantona_accantonato', array('action' => 'add')),
    'label' => 'Aggiungi un conto',
    'icon'  => 'plus'
));