<?php
$title = 'Add new category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('accantona_categoria', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('descrizione'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
