<?php
$title = 'Conti';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if ($rows): ?>
    <table class="table table-striped table-hover">
        <tr>
            <th>Nome</th>
            <th class="text-right">Operazioni</th>
        </tr>
        <?php foreach ($rows as $row) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($row->name); ?></td>
            <td class="text-right">
                <a href="<?php echo $this->url('accantonaAccount', array('action' => 'list', 'id' => $row->id)); ?>" class="btn btn-default" aria-label="Edit">
                    <span class="glyphicon glyphicon-list" aria-hidden="true" title="Lista"></span>
                </a>
                <a href="<?php echo $this->url('accantonaAccount', array('action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-default" aria-label="Edit">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true" title="Modifica"></span>
                </a>
                <!-- a href="<?php echo $this->url('accantona_categoria', array('action' => 'delete', 'id' => $row->id)); ?>" class="btn btn-default" aria-label="Edit">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Elimina"></span>
                </a -->
            </td>
        </tr>
        <?php endforeach; ?>

    </table>
<?php else: ?>
    <div>
        <i>Nessun conto definito, clicca sul tasto Aggiungi per crearne uno.</i>
    </div>
<?php endif; ?>
<div class="text-right">
    <a href="<?php echo $this->url('accantonaAccount', array('action' => 'add')); ?>" class="btn btn-default" aria-label="Add">
        <span class="glyphicon glyphicon-plus" aria-hidden="true" title="Aggiungi"></span> Add
    </a>
</div>
