version: "3.8"

services:
    web:
        container_name: ${PROJECT_NAME}_web_${VERSION_ID}
        build:
          context: ./docker/php-apache
          args:
              - XDEBUG=${XDEBUG}
        ports:
            - ${APACHE_PORT_EXPOSED}:80
        environment:
            APP_URL: ${APP_URL}
            TIME_ZONE: ${TIME_ZONE}
            DB_HOST: db:${DB_PORT_EXPOSED}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_NAME: ${DB_NAME}
        volumes:
            - .:/var/www/html
            - ./docker/php-apache/logs:/var/log/apache2
        depends_on:
            - db
    db:
        image: mysql:8.0.26
        container_name: ${PROJECT_NAME}_db_${VERSION_ID}
        ports:
            - ${DB_PORT_EXPOSED}:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/logs:/var/log/mysql
        environment:
            TZ: ${TIME_ZONE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
