<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var MoneyLog\Form\MovementForm $form
 * @var array<string> $searchParams
 * @var bool $isRepeatable
 * @var int $accountId
 */
?>
<?php echo $this->form()->openTag($form); ?>

    <?php echo $this->sbaFormRow($form->get('account')); ?>
    <?php echo $this->sbaFormRow($form->get('type')); ?>
    <?php echo $this->sbaFormRow($form->get('date')); ?>
    <?php echo $this->sbaFormRow($form->get('amount')); ?>
    <?php echo $this->sbaFormRow($form->get('description')); ?>
    <?php echo $this->sbaFormRow($form->get('category')); ?>

    <div class="text-right">
        <a class="btn btn-default" href="<?php echo $this->url('accantonaMovement', [], ['query' => $searchParams]); ?>">Annulla</a>
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Conferma</button>
    </div>
<?php echo $this->form()->closeTag(); ?>
