<style type="text/css">
    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
</style>
<?php
$this->form->setAttributes(array(
    'action' => $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password')),
    'class' => 'form-signin',
));
$this->form->prepare();
?>

<?= $this->form()->openTag($this->form); ?>
    <h1>Restore password</h1>

    <?php $element = $form->get('email'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?= $this->formSubmit($this->form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>