<?php
/**
 * @var Auth\Form\ForgottenPasswordForm $form
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$form->setAttributes(['action' => $this->url('auth_registration', ['action' => 'forgotten-password']), 'class' => 'form-signin']);
$form->prepare();
?>
<style type="text/css">
    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
</style>
<?= $this->form()->openTag($form); ?>
    <h1>Restore password</h1>

    <?php $element = $form->get('email'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
