<?php
/* @var Zend\View\Renderer\PhpRenderer $this */
$this->form->setAttributes(array(
    'action' => $this->url('auth/default', array('controller' => 'registration', 'action' => 'index')),
    'class' => 'form-signin',
));
$this->form->prepare();
?>
<style type="text/css">
    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin ul {
        color: #a94442;
        list-style-type: none;
        padding: 0;
    }
</style>
<?= $this->form()->openTag($this->form); ?>
    <h1>Registration</h1>

    <?php $element = $form->get('email'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?php $element = $form->get('password'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?php $element = $form->get('password_confirm'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?php $element = $form->get('captcha'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formCaptcha($element->setAttribute('class', 'form-control')); ?>
        <?= $errors; ?>
    </div>

    <!-- ?php echo $this->formLabel($form->get('captcha')); ?>
    < ?php echo $this->formCaptcha($form->get('captcha')->setAttribute('class', 'form-control')); ?>
    < ?php echo $this->formElementErrors($form->get('captcha')); ?>
    <!-- ?php echo $this->formInput($form->get('captcha')); ? -->
    <!-- ?php echo $this->formRow($this->form->get('captcha')); ? -->

    <?= $this->formSubmit($this->form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>