<?php
/* @var \Laminas\Form\Form $form */
$form->setAttributes(['action' => $this->url('auth_registration', ['action' => 'index']), 'class' => 'form-signin']);
$form->prepare();
?>
<style type="text/css">
    .form-signin {max-width: 330px; padding: 15px; margin: 0 auto;}
    .form-signin ul {color: #a94442; list-style-type: none; padding: 0;}
</style>
<?php echo $this->form()->openTag($this->form); ?>
    <h1>Registration</h1>

    <?php $element = $form->get('name'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('surname'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('email'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?php $element = $form->get('password'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?php $element = $form->get('password_confirm'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?php /*$element = $form->get('captcha');*/ ?>
    <?php /*$errors = $this->formElementErrors($element);*/ ?>
    <!-- div class="form-group <?php if ($errors) echo 'has-error'; ?>" -->
        <?php /*echo $this->formLabel($element);*/ ?>
        <?php /*echo $this->formCaptcha($element->setAttribute('class', 'form-control'));*/ ?>
        <?php /*echo $errors;*/ ?>
    <!-- /div -->

    <?= $this->formSubmit($this->form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
