<?php
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 * @var \Accantona\Form\AccantonatoForm $form
 */
$title = 'Movimenti';
$this->headTitle($title);
?>
<style type="text/css">
.has-error ul {
    color: #a94442;
    list-style-type: none;
    padding: 0;
}
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h2><?php echo $this->escapeHtml($account->name); ?></h2>
<form action="<?php echo $this->url('accantonaMoviment', array('action' => 'account', 'id' => $account->id)); ?>" method="post">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="valuta">Data</th>
                    <th class="amount text-right">Importo</th>
                    <th>Descrizione</th>
                    <th class="actions">&nbsp;</th>
                </tr>
                <tr id="search">
                    <td>
                        <select class="form-control" id="monthsFilter" name="monthsFilter">
                            <option value="0" <?php if ($months == 0) echo 'selected="selected"'; ?>>Tutte</option>
                            <option value="1" <?php if ($months == 1) echo 'selected="selected"'; ?>>Ultimo mese</option>
                            <option value="3" <?php if ($months == 3) echo 'selected="selected"'; ?>>Ultimi 3 mesi</option>
                            <option value="6" <?php if ($months == 6) echo 'selected="selected"'; ?>>Ultimi 6 mesi</option>
                            <option value="12" <?php if ($months == 12) echo 'selected="selected"'; ?>>Ultimo anno</option>
                        </select>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td class="text-right amount"><strong><?php echo $this->currencyForma($this->balanceStart); ?></strong></td>
                    <td><strong>Saldo precedente</strong></td>
                    <td></td>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($rows as $row): ?>
                <tr>
                    <td class="date"><?php echo $this->dateForma($row->date); ?></td>
                    <td class="text-right amount"><?php echo $this->currencyForma($row->amount); ?></td>
                    <td class="description"><?php echo $row->description; ?></td>
                    <td class="text-right">
                        <a href="<?php echo $this->url('accantonaMoviment', array('action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-default" title="Modifica">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </a>
                        <span data-href="<?php echo $this->url('accantonaMoviment', array('action' => 'delete', 'id' => $row->id)); ?>" class="btn btn-default delete-item" title="Elimina">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td class="text-right amount"><strong><?php echo $this->currencyForma($this->balanceEnd); ?></strong></td>
                    <td><strong>Saldo finale</strong></td>
                    <td></td>
                </tr>
                <tr>
                    <?php $element = $form->get('date'); ?>
                    <?php $errors = $this->formElementErrors($element); ?>
                    <td class="form-group <?php if ($errors) echo 'has-error'; ?>">
                        <?php echo $this->formInput($element); ?>
                        <?php echo $errors; ?>
                    </td>

                    <?php $element = $form->get('amount'); ?>
                    <?php $errors = $this->formElementErrors($element); ?>
                    <td class="form-group <?php if ($errors) echo 'has-error'; ?>">
                        <?php echo $this->formInput($element); ?>
                        <?php echo $errors; ?>
                    </td>

                    <?php $element = $form->get('description'); ?>
                    <?php $errors = $this->formElementErrors($element); ?>
                    <td class="form-group <?php if ($errors) echo 'has-error'; ?>">
                        <?php echo $this->formInput($element); ?>
                        <?php echo $errors; ?>
                    </td>

                    <td class="actions text-right">
                        <button id="save" type="submit" class="btn btn-default show-on-edit">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Aggiungi
                        </button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</form>
<script type="text/javascript">
    $('#search select').change(function(){
        location.href = "<?php echo $this->url(null, array('action' => 'account', 'id' => $account->id)); ?>" + '?monthsFilter=' + $('#monthsFilter').val();
    });

    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare l\'accantonamento selezionato?</h3>' +
            '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Importo</dt><dd>'  + button.parents('tr').find('.amount').html() + '</dd>' +
            '<dt>Data</dt><dd>'  + button.parents('tr').find('.date').html() + '</dd>' +
            '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });
</script>
