<?php
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 * @var \Accantona\Form\AccantonatoForm $form
 */
$chartData = array();
$morrisData = array();
?>
<style type="text/css">
    .has-error ul {
        color: #a94442;
        list-style-type: none;
        padding: 0;
    }
    #monthsFilter {
        margin: 8px 0;
    }
    #morris{
        height: 209px;
    }
</style>
<?php echo $this->pageHeader("Movimenti $account->name"); ?>
<div class="row">
    <div class="col-lg-4 col-md-5">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-euro fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            <?php echo $this->currencyForma($this->balanceEnd); ?>
                        </div>
                        <div>Saldo finale</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-filter fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            <select class="form-control" id="monthsFilter" name="monthsFilter">
                                <option value="0" <?php if ($months == 0) echo 'selected="selected"'; ?>>Tutte</option>
                                <option value="1" <?php if ($months == 1) echo 'selected="selected"'; ?>>Ultimo mese</option>
                                <option value="3" <?php if ($months == 3) echo 'selected="selected"'; ?>>Ultimi 3 mesi</option>
                                <option value="6" <?php if ($months == 6) echo 'selected="selected"'; ?>>Ultimi 6 mesi</option>
                                <option value="12" <?php if ($months == 12) echo 'selected="selected"'; ?>>Ultimo anno</option>
                            </select>
                        </div>
                        <div>Filtra</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-8 col-md-7">
        <div class="panel panel-default">
            <div id="morris"></div>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('accantonaMoviment', array('action' => 'account', 'id' => $account->id)); ?>" method="post">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="valuta">Data</th>
                    <th class="amount text-right">Importo</th>
                    <th>Descrizione</th>
                    <th class="actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($rows as $row): ?>
                    <?php
                    $strDate = $row->date->format('Y-m-d');
                    if (isset($chartData[$strDate])) {
                        $chartData[$strDate] += $row->amount;
                    } else {
                        $chartData[$strDate] = $row->amount;
                    }
                    ?>
                <tr>
                    <td class="date"><?php echo $this->dateForma($row->date); ?></td>
                    <td class="text-right amount"><?php echo $this->currencyForma($row->amount); ?></td>
                    <td class="description"><?php echo $row->description; ?></td>
                    <td class="text-right">
                        <a href="<?php echo $this->url('accantonaMoviment', array('action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-default" title="Modifica">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </a>
                        <span data-href="<?php echo $this->url('accantonaMoviment', array('action' => 'delete', 'id' => $row->id)); ?>" class="btn btn-default delete-item" title="Elimina">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</form>
<div id="chart_div"></div>

<script src="http://cdn.oesmith.co.uk/morris-0.5.1.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>

<script type="text/javascript">
    $('#monthsFilter').change(function(){
        location.href = "<?php echo $this->url(null, array('action' => 'account', 'id' => $account->id)); ?>" + '?monthsFilter=' + $('#monthsFilter').val();
    });

    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare l\'accantonamento selezionato?</h3>' +
            '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Importo</dt><dd>'  + button.parents('tr').find('.amount').html() + '</dd>' +
            '<dt>Data</dt><dd>'  + button.parents('tr').find('.date').html() + '</dd>' +
            '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });

    <?php
    foreach ($chartData as $strDate => $row) {
        $morrisData[] = array('x' => $strDate, 'y' => $row);
    }
    ?>

    Morris.Bar({
        element: 'morris',
        data: <?php echo json_encode($morrisData); ?>,
        xkey: 'x',
        ykeys: 'y',
        labels: ['Importo'],
        hideHover: "auto",
        resize: true,
        "xLabelFormat": function (x) { // <-- changed
            var d = x.label.split('-');
            return d[2] + '/' + d[1] + '/' + d[0];
        },
        "yLabelFormat": function (x) {
            var parts = x.toString().split(".");
            parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ".");
            return parts.join(",") + ' €';
        }
    });
</script>

<?php
$balanceHref = $this->url('accantonaAccount', array('action' => 'balance', 'id' => $account->id));
$this->floatingButtons()->addRawItem('
    <span data-href="' . $balanceHref . '" data-mfb-label="Conguaglia" class="balance mfb-component__button--child">
        <i class="mfb-component__child-icon glyphicon glyphicon-equalizer"></i>
    </span>
')
    ->addAnchorItem(array('href' => $this->url('accantonaMoviment', array('action' => 'add', 'id' => $account->id)), 'label' => 'Aggiungi transazione', 'icon' => 'plus'))
    ->addAnchorItem(array('href' => $this->url('accantonaMoviment', array('action' => 'move', 'id' => $account->id)), 'label' => 'Giroconto', 'icon' => 'transfer'));

$this->bindBalance('.balance');