<?php echo $this->pageHeader('Nuovo movimento'); ?>
<div class="row">
    <div class="col-lg-4">
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel panel-heading">
                Inserisci il nuovo movimento
            </div>
            <div class="panel panel-body">
                <?php echo $this->form()->openTag($this->form); ?>

                    <?php echo $this->sbaFormRow($form->get('date')); ?>
                    <?php echo $this->sbaFormRow($form->get('amount')); ?>
                    <?php echo $this->sbaFormRow($form->get('description')); ?>
                    <?php echo $this->sbaFormRow($form->get('category')); ?>

                    <div class="text-right">
                        <a class="btn btn-default" href="<?php echo $this->url('accantonaMoviment', array('action' => 'account', 'id' => $this->sourceAccount->id)) ?>">Annulla</a>
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Aggiungi movimento</button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
    </div>
</div>