<?php echo $this->pageHeader('Nuova transazione'); ?>
<?php echo $this->form()->openTag($this->form); ?>

    <?php $element = $form->get('date'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('amount'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('description'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <div class="text-right">
        <a class="btn btn-default" href="<?= $this->url('accantonaMoviment', array('action' => 'account', 'id' => $this->sourceAccount->id)) ?>">Annulla</a>
        <button type="submit" class="btn btn-primary">Aggiungi transazione</button>
    </div>

<?php echo $this->form()->closeTag(); ?>