<?php echo $this->pageHeader('Modifica movimento'); ?>
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">Modifica movimento</div>
            <div class="panel-body">
                <?php $this->form->setAttribute('action', $this->url('accantonaMoviment', ['action' => 'edit', 'id' => $this->item->id], ['query' => $searchParams])); ?>
                <?php $this->form->prepare(); ?>
                <?php echo $this->form()->openTag($this->form); ?>

                    <?php echo $this->sbaFormRow($form->get('date')); ?>
                    <?php echo $this->sbaFormRow($form->get('amount')); ?>
                    <?php echo $this->sbaFormRow($form->get('description')); ?>
                    <?php echo $this->sbaFormRow($form->get('category')); ?>

                    <div class="text-right">
                        <a class="btn btn-default" href="<?php echo $this->url('accantonaMoviment', ['action' => 'account', 'id' => $this->item->accountId], ['query' => $searchParams]) ?>">Annulla</a>
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Salva</button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4"></div>
</div>