<?php
$title = 'Giroconto';
$this->headTitle($title);
//$this->form->setAttribute('action', $this->url('accantonaAccount', array('action' => 'edit', 'id' => $this->id)));
//$this->form->prepare();
?>
<?php echo $this->pageHeader($title); ?>
<h2>Preleva da <?php echo $this->sourceAccount->name; ?></h2>
<?php echo $this->form()->openTag($this->form); ?>

    <?php $element = $form->get('date'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('amount'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('description'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('targetAccountId'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formSelect($element); ?>
        <?php echo $errors; ?>
    </div>

    <div class="text-right">
        <a class="btn btn-default" href="<?= $this->url('accantonaMoviment', array('action' => 'account', 'id' => $this->sourceAccount->id)) ?>">Annulla</a>
        <button type="submit" class="btn btn-primary">Sposta</button>
    </div>

<?php echo $this->form()->closeTag(); ?>
