<h1>Login </h1>
<?php
echo $this->escapeHtml($this->messages);

$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('rememberme'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<?php if ($user = $this->identity()): ?>
    Logged in as <?php echo $this->escapeHtml($user->name); ?>
    | <a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
<?php else: ?>
    Not logged in
<?php endif; ?>
<p>
    <a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a>
    |
    <a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>