<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var MoneyLog\Form\CategoryForm $form
 * @var string $id
 */
$form->setAttribute('action', $this->url('accantona_categoria', array('action' => 'edit', 'id' => $id)));
$form->prepare();
?>
<?php echo $this->pageHeader('Modifica categorie'); ?>
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Modifica categoria di spesa
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>

                    <?php echo $this->formHidden($form->get('id')); ?>
                    <?php echo $this->sbaFormRow($form->get('description')); ?>

                    <?php
                    $element = $form->get('active');
                    $element->setLabelAttributes(array('for' => 'categotyStatus'));
                    $errors = $this->formElementErrors($element);
                    ?>
                    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
                        <?php $errors = $this->formElementErrors($element); ?>
                        <div class="checkbox <?php if ($errors) echo 'has-error'; ?>">
                            <label><?php echo $this->formCheckbox($element); ?> Attivo</label>
                        </div>
                        <?php echo $errors; ?>
                    </div>

                    <div class="text-right">
                        <button id="save" type="submit" class="btn btn-default show-on-edit" aria-label="Salva">
                            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Salva
                        </button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4"></div>
</div>
