<?php
/**
 * @var array<\Application\Entity\Category> $rows
 */
echo $this->pageHeader('Categorie di spesa');
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Lista categories
            </div>
            <div class="panel-body table-responsive">
                <table class="table table-striped table-bordered table-hover" id="my-table">
                    <thead>
                        <tr>
                            <th>Descrizione</th>
                            <th>Attivo</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <?php foreach ($rows as $row) : ?>
                    <tr>
                        <td class="description"><?php echo $this->escapeHtml($row->getDescrizione()); ?></td>
                        <td class="status"><?php echo $row->getStatus() ? 'Sì' : 'No'; ?></td>
                        <td class="text-right">
                            <a href="<?php echo $this->url('accantona_categoria', ['action' => 'edit', 'id' => $row->getId()]); ?>" class="btn btn-default btn-xs" title="Modifica">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </a>
                            <span data-href="<?php echo $this->url('accantona_categoria', ['action' => 'delete', 'id' => $row->getId()]); ?>" class="btn btn-default btn-xs delete-item" title="Elimina">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </span>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare la categoria selezionata?</h3>' +
            '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Attivo</dt><dd>'  + button.parents('tr').find('.status').html() + '</dd>' +
            '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });
</script>
<?php
$this->dataTable('#my-table', ['columnDefs' => [
    ["targets" => -1, "orderable" => false]     // azioni
]]);
$this->floatingButtons()->addAnchorItem(array(
    'href' => $this->url('accantona_categoria', array('action' => 'add')),
    'label' => 'Aggiungi una categoria',
    'icon' => 'plus'
));
