<?php
/* @var \Accantona\Form\SpesaForm $form */

$title = 'Aggiungi spesa';
$this->headTitle($title);
$this->form->setAttribute('action', $this->url('accantona_spesa', array('action' => 'add')));
$this->form->prepare();
?>
<?php echo $this->pageHeader($title); ?>
<div class="form-group" style="margin:auto;max-width:800px;">
    <?php echo $this->form()->openTag($this->form); ?>

    <?php $element = $form->get('valuta'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element->setValue(date('Y-m-d'))); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('id_categoria'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formSelect($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('importo'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('descrizione'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('accountId'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formSelect($element); ?>
        <?php echo $errors; ?>
    </div>

    <div class="text-right">
        <a class="btn btn-default" href="<?= $this->url('accantona_spesa') ?>">Annulla</a>
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Salva</button>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</div>
