<?php echo $this->pageHeader('Spese'); ?>
<div class="row" id="search">
    <?php
    echo $this->widgetText([
        'color'     => 'primary',
        'col-lg'    => '4',
        'col-md'    => '4',
        'fa'        => 'eur',
        'label'     => 'Totale',
        'text'      => $this->currencyForma($this->sum)
    ]);
    echo $this->widgetSelect([
        'col-lg'    => '4',
        'col-md'    => '4',
        'color'     => 'green',
        'fa'        => 'filter',
        'id'        => 'categoryIdFilter',
        'label'     => 'Categoria',
        'name'      => 'monthsFilter',
        'options'   => $this->categoryOptions,
        'selected'  => $categoryId,
    ]);
    echo $this->widgetSelect([
        'col-lg'    => '4',
        'col-md'    => '4',
        'color'     => 'green',
        'fa'        => 'filter',
        'id'        => 'monthsFilter',
        'label'     => 'Periodo',
        'name'      => 'monthsFilter',
        'options'   => [0 => 'Tutte', 1 => 'Ultimo mese', 3 => 'Ultimi 3 mesi', 6 => 'Ultimi 6 mesi', 12 => 'Ultimo anno'],
        'selected'  => $months,
    ]);
    ?>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body table-responsive">
                <table class="table table-striped table-bordered table-hover responsive" id="my-table">
                    <thead>
                        <tr>
                            <th class="category">Categoria</th>
                            <th>Data</th>
                            <th>Importo</th>
                            <th>Descrizione</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($rows as $row) : ?>
                        <tr>
                            <td class="category"><?php echo $this->escapeHtml($row->category->descrizione); ?></td>
                            <td class="date"><?php echo $this->dateForma($row->valuta); ?></td>
                            <td class="amount text-right"><?php echo $this->currencyForma($row->importo); ?></td>
                            <td><?php echo $this->escapeHtml($row->descrizione); ?></td>
                            <td class="actions text-right">
                                <a href="<?php echo $this->url('accantona_spesa', array('action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-default" title="Modifica">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <span data-href="<?php echo $this->url('accantona_spesa', array('action' => 'delete', 'id' => $row->id)); ?>" class="btn btn-default delete-item" title="Elimina">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </span>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#search select').change(function(){
        location.href = "<?php echo $this->url('accantona_spesa', array('action' => 'index')); ?>"
                      + '?categoryIdFilter=' + $('#categoryIdFilter').val()
                      + '&monthsFilter=' + $('#monthsFilter').val();
    });

    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare la spesa selezionata?</h3>' +
        '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Importo</dt><dd>'  + button.parents('tr').find('.amount').html() + '</dd>' +
            '<dt>Data</dt><dd>'  + button.parents('tr').find('.date').html() + '</dd>' +
            '<dt>Categoria</dt><dd>'  + button.parents('tr').find('.category').html() + '</dd>' +
        '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });

    $(document).ready(function(){
        $('#my-table').DataTable({
            "columnDefs": [
                {"targets": 1, "type": 'date-eu'},      //data
                {"targets": 2, "type": 'currency-it'},  //importo
                {"orderable": false, "targets": -1}     //azioni
            ],
            "language":{
                "url": "/vendor/datatables-plugins/i18n/Italian.json"
            },
            "order": [
                [0, "desc"]
            ],
            "responsive": true
        });
    });
</script>
<?php
$this->floatingButtons()->addAnchorItem(array(
    'href'  => $this->url('accantona_spesa', array('action' => 'add')),
    'label' => 'Aggiungi una spesa',
    'icon'  => 'plus',
));