<?php
/**
 * @var \Laminas\Form\Form $form
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$title = 'Aggiungi un nuovo conto';
$this->headTitle($title);

$form->setAttribute('action', $this->url('accantonaAccount', array('action' => 'add')));
$form->prepare();
?>
<?php echo $this->pageHeader($title); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>

    <?php $element = $form->get('name'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formLabel($element); ?>
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

    <?php $element = $form->get('recap'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <label><?php echo $this->formCheckbox($element); ?> Includi nel riepilogo</label>
        <?php echo $errors; ?>
    </div>

    <input type="hidden" name="closed" value="0" />

    <?php $element = $form->get('submit'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group text-right <?php if ($errors) echo 'has-error'; ?>">
        <?= $this->formInput($element); ?>
        <?= $errors; ?>
    </div>

<?php echo $this->form()->closeTag(); ?>
