<?php
/** @var \Zend\Form\Form $form */

$title = 'Modifica conto';
$this->headTitle($title);
$this->form->setAttribute('action', $this->url('accantonaAccount', array('action' => 'edit', 'id' => $this->id)));
$this->form->prepare();
?>
<?php echo $this->pageHeader($title); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>

    <?php $element = $form->get('name'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('recap'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <label><?php echo $this->formCheckbox($element); ?> Includi nel riepilogo</label>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('closed'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <label><?php echo $this->formCheckbox($element); ?> Chiudi il conto</label>
        <?php echo $errors; ?>
    </div>

    <?php $element = $form->get('submit'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group text-right <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

<?php echo $this->form()->closeTag(); ?>
