<?php
/**
 * @var Laminas\Form\Form $form
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var string $id
 */
$title = 'Modifica conto';
$this->headTitle($title);
$form->setAttribute('action', $this->url('accantonaAccount', array('action' => 'edit', 'id' => $id)));
$form->prepare();
?>
<?php echo $this->pageHeader($title); ?>
<div class="row">
    <div class="col-lg-4 col-lg-offset-4">


        <div class="panel panel-default">

            <div class="panel-heading">
                <?php echo $title; ?>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>

                <?php $element = $form->get('name'); ?>
                <?php $errors = $this->formElementErrors($element); ?>
                <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
                    <?php echo $this->formLabel($element); ?>
                    <?php echo $this->formInput($element); ?>
                    <?php echo $errors; ?>
                </div>

                <?php echo $this->sbaFormRow($form->get('status')); ?>

                <div class="form-group text-center">
                    <input type="submit" name="submit" class="btn btn-primary" id="submitbutton" value="Salva">
                </div>

                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>


    </div>
</div>
