<?php $sum = 0; ?>
<?php echo $this->pageHeader('Dashboard'); ?>
<div class="row">
    <?php
    echo $this->widgetText([
        'color' => 'yellow',
        'col-lg' => $remainingDays ? 3 : 12,
        'col-md' => $remainingDays ? 6 : 12,
        'fa' => 'eur',
        'label' => 'Budget residuo',
        'text' => $this->currencyForma($monthBudget),
    ]);

    if ($remainingDays) {
        echo $this->widgetText([
            'color' => 'primary',
            'col-lg' => 3,
            'col-md' => 6,
            'fa' => 'calendar',
            'label' => 'Giorni residui',
            'text' => $remainingDays,
        ]);
        echo $this->widgetText([
            'color' => 'green',
            'col-lg' => 3,
            'col-md' => 6,
            'fa' => 'eur',
            'label' => 'Budget giornaliero oggi',
            'text' => $this->currencyForma($monthBudget / $remainingDays),
        ]);
        echo $this->widgetText([
            'color' => 'green',
            'col-lg' => 3,
            'col-md' => 6,
            'fa' => 'eur',
            'label' => 'Budget giornaliero domani',
            'text' => $remainingDays > 1 ? $this->currencyForma($monthBudget / ($remainingDays - 1)) : 'n/a',
        ]);
    }
    ?>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Budget</h2>
            </div>
            <div class="panel-body">
                <?php if (!$accounts): ?>
                    <div class="alert alert-warning" role="alert">
                        <p>
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            Non hai ipostato alcun conto nel riepilogo.
                        </p>
                        <p>
                            Impostando i conti nel riepilogo (es. Contanti, Conto corrente, ecc.) ti verranno siggeriti i budget giornalieri e il residuo spendibile fino
                            al prossimo stipendio.
                        </p>
                        <p>
                            Clicca <a href="<?php echo $this->url('accantonaAccount'); ?>">qui</a> per crearne o impostarne uno.
                        </p>
                    </div>
                <?php endif; ?>
                <form action="<?php echo $this->url('accantona_recap', array('action' => 'edit')); ?>" method="post">
                    <table class="table">
                        <thead><tr><th>Descrizione</th><th class="text-right">Valore</th></tr></thead>
                        <tbody>

                            <?php foreach ($accounts as $account): ?>
                                <tr>
                                    <td>
                                        <a href="<?php echo $this->url('accantonaMoviment', array('action' => 'account', 'id' => $account['id'])); ?>"><?php echo $account['name']; ?></a>
                                    </td>
                                    <td class="text-right" style="min-width:130px;">
                                        <?php echo $this->currencyForma($account['total']); ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            <tr>
                                <td>Risparmio</td>
                                <td class="text-right" style="min-width:130px;">
                                    -
                                    <input class="form-control show-on-edit text-right" disabled="disabled" name="risparmio" step="0.01" style="display:none;width:100px;" type="number" value="<?php echo number_format($variables['risparmio'], 2, '.', ''); ?>" />
                                    <span class="hide-on-edit"><?php echo $this->currencyForma($variables['risparmio']); ?></span>
                                </td>
                            </tr>
                            <tr>
                                <td>Accantonati</td>
                                <td class="text-right">
                                    <?php echo '- ' . $this->currencyForma($stored); ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="text-right">
                        <button id="edit" type="button" class="btn btn-default hide-on-edit" aria-label="Modifica">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Modifica
                        </button>
                        <button id="cancel" type="button" class="btn btn-default show-on-edit" aria-label="Salva" style="display: none;">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Annulla
                        </button>
                        <button id="save" type="submit" class="btn btn-default show-on-edit" aria-label="Salva" style="display: none;">
                            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Salva
                        </button>
                    </div>
                </form>
                <div id="donut-accounts"></div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Spese per categoria</h2>
            </div>
            <div class="panel-body">
                <?php if ($avgPerCategory): ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Categoria</th>
                        <th class="text-right">Spesa media mensile</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($avgPerCategory as $row) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($row['description']); ?></td>
                            <td class="text-right">
                                <?php
                                if ($row['average'] < 0) {
                                    $average = abs($row['average']);
                                    $sum += $average;
                                    echo $this->currencyForma($average);
                                }
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td><strong>Somma</strong></td>
                        <td class="text-right"><strong><?php echo $this->currencyForma($sum); ?></strong></td>
                    </tr>
                    </tfoot>
                </table>
                <?php else: ?>
                    <div class="alert alert-danger" role="alert">
                        <p>
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            Non è stata definita alcuna categoria di spesa.
                        </p>
                        <p>
                            Le categorie di spesa ti aiutano monitorare le voci di spesa per te più significative
                            (es.&nbsp;Casa, Auto, Gas, ecc.).
                        </p>
                        <p>
                            Clicca <a href="<?php echo $this->url('accantona_categoria', array('action' => 'add')); ?>">qui</a> per crearne una.
                        </p>
                    </div>
                <?php endif; ?>
                <div id="donut-spends"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#edit').click(function () {
        $('.hide-on-edit').hide();
        $('.show-on-edit').prop('disabled', false).show().css('display', 'inline');
    });
    $('#cancel').click(function () {
        $('.hide-on-edit').show();
        $('.show-on-edit').prop('disabled', true).hide();
    });
    $('#save').click(function () {
        $('form').submit();
    });
</script>
<?php
if ($this->donutSpends) {
    $this->morris()->donut('donut-spends', $this->donutSpends);
}
if ($this->donutAccounts) {
    $this->morris()->donut('donut-accounts', $this->donutAccounts);
}