<?php
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 * @var \Accantona\Form\AccantonatoForm $form
 */
?>
<?php echo $this->pageHeader('Accantonati'); ?>
<div class="row">
    <?php echo $this->widgetText(['color' => 'green', 'col-lg' => '12', 'fa' => 'eur', 'label' => 'Saldo', 'text' => $this->currencyForma($this->balance)]); ?>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <form>
                        <div class="col-lg-3 col-md-6">
                            <label>Dal</label>
                            <input class="form-control" name="dateMin" type="date" value="<?php echo $searchParams['dateMin']; ?>"/>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <label>Al</label>
                            <input class="form-control" name="dateMax" type="date" value="<?php echo $searchParams['dateMax']; ?>"/>
                        </div>
                        <div class="col-lg-4 col-md-12">
                            <label>Descrizione</label>
                            <input name="description" type="text" class="form-control" placeholder="Descrizione" value="<?php echo $searchParams['description']; ?>">
                        </div>
                        <div class="col-lg-2 col-md-12">
                            <label>&nbsp;</label>
                            <button type="submit" class="form-control btn btn-primary" value="cerca"><i class="fa fa-search"></i> Cerca</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="accantonati">
                    <thead>
                        <tr>
                            <th>Valuta</th>
                            <th>Importo</th>
                            <th>Descrizione</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($rows as $row): ?>
                        <tr>
                            <td class="date"><?php echo $this->dateForma($row->valuta); ?></td>
                            <td class="amount text-right"><?php echo $this->currencyForma($row->importo); ?></td>
                            <td class="description"><?php echo $row->descrizione; ?></td>
                            <td class="text-right">
                                <a href="<?php echo $this->url('accantona_accantonato', ['action' => 'edit', 'id' => $row->id], ['query' => $searchParams]); ?>" class="btn btn-default" title="Modifica">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <span data-href="<?php echo $this->url('accantona_accantonato', ['action' => 'delete', 'id' => $row->id], ['query' => $searchParams]); ?>" class="btn btn-default delete-item" title="Elimina">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </span>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare l\'accantonamento selezionato?</h3>' +
            '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Importo</dt><dd>'  + button.parents('tr').find('.amount').html() + '</dd>' +
            '<dt>Data</dt><dd>'  + button.parents('tr').find('.date').html() + '</dd>' +
            '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });
    $(document).ready(function(){
        $('#accantonati').DataTable({
            "columnDefs": [
                {"targets": 0, "type": 'date-eu'},      //data
                {"targets": 1, "type": 'currency-it'},  //importo
                {"orderable": false, "targets": -1}     //azioni
            ],
            "language":{
                "url": "/js/data-table-Italian.json"
            },
            "order": [
                [0, "desc"]
            ],
            "responsive": true,
            "searching": false
        });
    });
</script>
<?php
$this->floatingButtons()->addAnchorItem(array(
    'href'  => $this->url('accantona_accantonato', array('action' => 'add')),
    'icon'  => 'plus',
    'label' => 'Nuovo movimento',
));