<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $content
 */ ?>
<!doctype html>
<html lang="it">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle('MoneyLog')->setSeparator('|')->setAutoEscape(false); ?>
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/wallet_32x28.png']); ?>
    <?php  echo $this->headScript(); ?>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/css/page/dashboard-index.css" rel="stylesheet">
</head>
<body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="<?php echo $this->url('accantona_recap'); ?>">
        <img alt="" src="/img/wallet-white.svg" width="20" /> MoneyLog
    </a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="#">Sign out</a>
        </div>
    </div>
</header>

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?php echo $this->url('accantona_recap'); ?>">
                            <span data-feather="home"></span> Cruscotto
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo $this->url('accantona_categoria'); ?>">
                            <span data-feather="tag"></span> Categorie
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo $this->url('accantonaAccount'); ?>">
                            <span data-feather="file"></span> Conti
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo $this->url('accantonaMovement'); ?>">
                            <span data-feather="file-text"></span> Movimenti
                        </a>
                    </li>
                    <?php if ($this->userData()->hasStored()): ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo $this->url('accantona_accantonato'); ?>">
                            <span data-feather="layers"></span> Accantonati
                        </a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
        </nav>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <?php echo $content;?>
        </main>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

</body>
</html>
