<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?php
        echo $this->headTitle('EasyWallet')->setSeparator('|')->setAutoEscape(false);

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        // Le styles
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/wallet_32x28.png'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'));

        // Scripts
        echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

        <!-- google charts -->
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

        <!-- jquery.cookiebar -->
        <link href="/js/jquery.cookiebar/jquery.cookiebar.css" media="screen" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="/js/jquery.cookiebar/jquery.cookiebar.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                var cookieBarOptions = {
                    acceptText: 'Accetto',
                    "bottom": true,
                    "fixed": true,
                    "message": 'Questo sito utilizza i cookies per migliorare la vostra esperienza.',
//                    "policyButton": true,
//                    "policyText": 'Privacy Policy',
//                    "policyURL": '/privacy-policy',
                    "zindex": 1
                };
                if ($.cookieBar(cookieBarOptions)) {
                }
            });
        </script>

        <style type="text/css">
            .app-env{
                position: fixed;
                right: 0;
                top: 0;
                z-index: 1031;
            }
            .app-env span{
                font-weight: bold;
                background-color: #f00;
                padding: 3px;
                color: #fff;
            }
        </style>
    </head>
    <body>
        <?php if (APP_ENV != 'production'): ?>
            <div class="app-env"><span><?php echo APP_ENV; ?></span></div>
        <?php endif; ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="/img/wallet_32x32.png" alt="Accantona"/></a>
                </div>
                <?php if ($this->identity()): ?>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<?php if (false) echo 'active'; ?>">
                            <a href="<?php echo $this->url('accantona_recap') ?>"><?php echo $this->translate('Riepilogo'); ?></a>
                        </li>
                        <li class="<?php if (false) echo 'active'; ?>">
                            <a href="<?php echo $this->url('accantona_spesa') ?>"><?php echo $this->translate('Spese'); ?></a>
                        </li>
                        <li class="<?php if (false) echo 'active'; ?>">
                            <a href="<?php echo $this->url('accantona_categoria') ?>"><?php echo $this->translate('Categorie'); ?></a>
                        </li>
                        <li class="<?php if (false) echo 'active'; ?>">
                            <a href="<?php echo $this->url('accantonaAccount') ?>"><?php echo $this->translate('Conti'); ?></a>
                        </li>
                        <li class="<?php if (false) echo 'active'; ?>">
                            <a href="<?php echo $this->url('accantona_accantonato'); ?>"><?php echo $this->translate('Accantonati'); ?></a>
                        </li>
                        <li class="<?php if (false) echo 'active'; ?>">
                            <a href="<?php echo $this->url('accantonaSettings'); ?>"><?php echo $this->translate('Settings'); ?></a>
                        </li>
                        <li class="<?php if (false) echo 'active'; ?>">
                            <a href="<?php echo $this->url('auth/default', array('action' => 'logout')); ?>"><?php echo $this->translate('Logout'); ?></a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
                <?php endif; ?>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2015 - <?= date('Y') ?> by Fabio Ventura. Tutti i diritti riservati.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript(); ?>
        <!-- bootbox code -->
        <script src="/js/node_modules/bootbox/bootbox.min.js"></script>
    </body>
</html>
