<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <?php
        echo $this->headTitle('EasyWallet')->setSeparator('|')->setAutoEscape(false);
        echo $this->headMeta();

        // Le styles
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/wallet_32x28.png'));

        // Scripts
        echo $this->headScript();
        ?>

        <!-- my CSS -->
        <link href="/css/style.css" rel="stylesheet" />

        <!-- Bootstrap Core CSS -->
        <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="/dist/css/sb-admin-2.css" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="/vendor/morrisjs/morris.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- DataTables CSS -->
        <link href="/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
        <link href="/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- jQuery -->
        <script src="/vendor/jquery/jquery.min.js"></script>

        <!-- google charts -->
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

        <!-- jquery.cookiebar -->
        <link href="/js/jquery.cookiebar/jquery.cookiebar.css" media="screen" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="/js/jquery.cookiebar/jquery.cookiebar.js"></script>

        <!-- begin google analitics code -->
        <script type="text/javascript">
            $(document).ready(function(){
                $.cookieBar({
                    "acceptText": 'Conferma',
                    "bottom": true,
                    "fixed": true,
                    "message": "Questo sito usa i cookies, continuando la navigazione assumiamo che tu ne accetti l'utilizzo.",
                    "policyButton": true,
                    "policyText": 'Privacy Policy',
                    "policyURL": '/privacy-policy',
                    "zindex": 1
                });

                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
                ga('create', 'UA-79448446-1', 'auto');
                ga('send', 'pageview');
            });
        </script>
        <!-- end google analitics code -->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('accantona_recap'); ?>"><img alt="" src="/img/wallet.svg" style="display: inline; vertical-align: middle; width: 30px;" /> <span style="vertical-align: middle;">EasyWallet</span></a>
                </div>
                <!-- /.navbar-header -->
                <?php
                /* @var stdClass $identity */
                $identity = $this->identity();
                ?>
                <?php if ($this->identity()): ?>
                <ul class="nav navbar-top-links navbar-right">
                    <!-- /.dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> <?php echo $identity->name . ' ' . $identity->surname; ?> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="<?php echo $this->url('auth/default', array('action' => 'update')); ?>"><i class="fa fa-edit fa-fw"></i> Utente</a></li>
                            <li><a href="<?php echo $this->url('accantonaSettings'); ?>"><i class="fa fa-gear fa-fw"></i> <?php echo $this->translate('Settings'); ?></a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url('auth/default', array('action' => 'logout')); ?>"><i class="fa fa-sign-out fa-fw"></i> <?php echo $this->translate('Logout'); ?></a></li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li><a href="<?php echo $this->url('accantona_recap'); ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a></li>
                            <li><a href="<?php echo $this->url('accantona_categoria'); ?>"><i class="fa fa-table fa-fw"></i> <?php echo $this->translate('Categorie'); ?></a></li>
                            <li><a href="<?php echo $this->url('accantonaAccount'); ?>"><i class="fa fa-table fa-fw"></i> <?php echo $this->translate('Conti'); ?></a></li>
                            <li><a href="<?php echo $this->url('accantona_accantonato'); ?>"><i class="fa fa-table fa-fw"></i> <?php echo $this->translate('Accantonati'); ?></a></li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <?php endif; ?>
                <!-- /.navbar-static-side -->
            </nav>

            <div id="page-wrapper">
                <?php echo $this->content; ?>
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->
        <hr />
        <footer>
            <p class="text-center">&copy; 2015 - <?php echo date('Y'); ?> by Fabio Ventura. Tutti i diritti riservati. - <a href="/privacy-policy">Privacy policy</a></p>
        </footer>

        <?php echo $this->floatingButtons(); ?>

        <!-- Bootstrap Core JavaScript -->
        <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/vendor/metisMenu/metisMenu.min.js"></script>

        <!-- Morris Charts JavaScript -->
        <script src="/vendor/raphael/raphael.min.js"></script>
        <script src="/vendor/morrisjs/morris.min.js"></script>
        <script src="../data/morris-data.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="../dist/js/sb-admin-2.js"></script>

        <!-- bootbox code -->
        <script src="/js/node_modules/bootbox/bootbox.min.js"></script>

        <!-- DataTables JavaScript -->
        <script src="/vendor/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
        <script src="/vendor/datatables-plugins/dataTables.bootstrap.min.js" type="text/javascript"></script>
        <script src="/vendor/datatables-responsive/dataTables.responsive.js" type="text/javascript"></script>
        <script src="/vendor/datatables-plugins/sorting/date-eu.js" type="text/javascript"></script>
        <script src="/vendor/datatables-plugins/sorting/currency-it.js" type="text/javascript"></script>
        <?php echo $this->richInlineScript(); ?>
    </body>
</html>
