<!DOCTYPE html>
<html lang="it">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <?php echo $this->headTitle('MoneyLog')->setSeparator('|')->setAutoEscape(false); ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/wallet_32x28.png']); ?>
        <link rel="manifest" href="/manifest.json">
        <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" /><!-- Bootstrap Core CSS -->
        <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet" /><!-- MetisMenu CSS -->

        <!-- Custom CSS -->
        <link href="/dist/css/sb-admin-2.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- jQuery -->
        <script src="../vendor/jquery/jquery.min.js"></script>

        <!-- jquery.cookiebar -->
        <link href="/js/jquery.cookiebar/jquery.cookiebar.css" media="screen" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="/js/jquery.cookiebar/jquery.cookiebar.js"></script>
        <?php echo $this->commonJavascript(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?php echo $this->url('accantona_recap'); ?>"><img alt="" src="/img/wallet.svg" style="display: inline; vertical-align: middle; width: 30px;" /> <span style="vertical-align: middle;">MoneyLog</span></a>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <hr />
        <?php echo $this->footer(); ?>

        <!-- Bootstrap Core JavaScript -->
        <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/vendor/metisMenu/metisMenu.min.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="/dist/js/sb-admin-2.js"></script>
    </body>
</html>
