<?php echo $this->pageHeader('Impostazioni'); ?>
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">Modifica Impostazioni</div>
            <div class="panel-body">
                <?php $this->form->setAttribute('action', $this->url()); ?>
                <?php $this->form->prepare(); ?>
                <?php echo $this->form()->openTag($this->form); ?>

                <?php echo $this->sbaFormRow($form->get('payDay'), 'Se impostato, viene visualizzato nel cruscotto il calcolo dei giorni mancanti al prossimo stipendio e il budget medio giornaliero fino al prossimo stipendio.'); ?>
                <?php echo $this->sbaFormRow($form->get('monthsRetrospective'), 'Numero di mesi utilizzatto per la statistica della media delle spese.'); ?>
                <?php echo $this->sbaFormRow($form->get('stored'), 'L\'accantonamento è una quota del budget che serve a coprire le spese categorizzate'); ?>

                <div class="text-right">
                    <input class="form-control btn-primary" type="submit" value="Salva" />
                </div>
                <?php echo $this->form()->closeTag(); ?>
                <?php if ($message): ?>
                    <br />
                    <div class="alert alert-success"><?php echo $message; ?></div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4"></div>
</div>