<?php
/**
 * @var Application\Entity\Account $account
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array<\Application\Entity\Category> $categories
 * @var array<\Application\Entity\Movement> $rows
 * @var array<array> $dataLineChart
 * @var array<string> $searchParams
 * @var float $balanceAccount
 * @var float $balanceAvailable
 */
$chartData = array();
$morrisData = array();
?>
<style type="text/css">
    .has-error ul {
        color: #a94442;
        list-style-type: none;
        padding: 0;
    }
    #monthsFilter {
        margin: 8px 0;
    }
</style>
<?php echo $this->pageHeader("Movimenti {$account->getName()}"); ?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <?php echo $this->widgetText(['color' => 'green', 'col-lg' => 6, 'col-md' => 6, 'fa' => 'eur', 'label' => 'Saldo disponibile', 'text' => $this->currencyForma($balanceAvailable)]); ?>
            <?php echo $this->widgetText(['color' => 'green', 'col-lg' => 6, 'col-md' => 6, 'fa' => 'eur', 'label' => 'Saldo contabile', 'text' => $this->currencyForma($balanceAccount)]); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Filtri</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->synopsisFilters($searchParams, $categories); ?>
                        <a class="btn btn-default btn-circle pull-right" id="monthsFilterToggle"><i class="fa fa-chevron-down"></i></a>
                    </div>
                </div>
                <form class="collapse" id="collapseFilters">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label>Descrizione</label>
                                <input name="description" type="text" class="form-control" placeholder="Descrizione" value="<?php echo $searchParams['description']; ?>">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label>Categoria</label>
                                <select class="form-control" name="category">
                                    <option></option>
                                    <?php foreach ($categories as $category): ?>
                                        <option value="<?php echo $category->getId(); ?>"<?php if ($category->getId() == $searchParams['category']) echo ' selected="selected"'?>>
                                            <?php echo $category->getDescription(); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Dal</label>
                                <input class="form-control" name="dateMin" type="date" value="<?php echo $searchParams['dateMin']; ?>"/>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Al</label>
                                <input class="form-control" name="dateMax" type="date" value="<?php echo $searchParams['dateMax']; ?>"/>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Importo minimo</label>
                                <input class="form-control" name="amountMin" type="number" step="0.01" value="<?php echo $searchParams['amountMin']; ?>"/>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Impoto massimo</label>
                                <input class="form-control" name="amountMax" type="number" step="0.01" value="<?php echo $searchParams['amountMax']; ?>"/>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <button type="button" class="form-control btn btn-danger" value="Azzera" id="remove-filters"><i class="fa fa-remove"></i> Rimuovi filtri</button>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary" value="cerca"><i class="fa fa-search"></i> Cerca</button>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Lista movimenti</h4>
            </div>
            <div class="panel-body table-responsive">
                <table class="table table-striped table-bordered table-hover responsive" id="my-table" data-page-length="25">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th style="min-width: 70px;">Importo</th>
                            <th>Descrizione</th>
                            <th>Categoria</th>
                            <th>Azioni</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($rows as $row): ?>
                            <?php
                            $strDate = $row->getDate()->format('Y-m-d');
                            if (!isset($chartData[$strDate])) {
                                $chartData[$strDate] = ['in' => 0, 'out' => 0];
                            }
                            $row->getAmount() > 0 ? $chartData[$strDate]['in']  += $row->getAmount()
                                                  : $chartData[$strDate]['out'] += $row->getAmount();
                            ?>
                        <tr>
                            <td class="date"><?php echo $this->dateForma($row->getDate()); ?></td>
                            <td class="text-right amount"><?php echo $this->currencyForma($row->getAmount()); ?></td>
                            <td class="description"><?php echo $row->getDescription(); ?></td>
                            <td class="description"><?php echo null !== ($c = $row->getCategory()) ? $c->getDescription() : ''; ?></td>
                            <td class="text-right">
                                <a href="<?php echo $this->url('accantonaMovement', ['action' => 'edit', 'id' => $row->getId()], ['query' => $searchParams]); ?>" class="btn btn-default btn-xs" title="Modifica">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <span data-href="<?php echo $this->url('accantonaMovement', ['action' => 'delete', 'id' => $row->getId()], ['query' => $searchParams]); ?>" class="btn btn-default btn-xs delete-item" title="Elimina">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </span>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?php if ($rows): ?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Movimenti nel mese
            </div>
            <div class="panel-body">
                <div id="morris" style="height:200px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Andamento del saldo
            </div>
            <div class="panel-body">
                <div id="balance-chart" style="height:200px;"></div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<?php
echo $this->balanceModalForm($account->getId(), 'accantonaMovement');
// prepare data for barchar
foreach ($chartData as $strDate => $row) {
    $morrisData[] = ['x' => $strDate, 'in' => $row['in'], 'out' => abs($row['out'])];
}
usort($morrisData, function ($a, $b) {
    if ($a['x'] == $b['x']) {
        return 0;
    }
    return $a['x'] < $b['x'] ? -1 : 1;
});
?>
<script type="text/javascript">
    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare l\'accantonamento selezionato?</h3>' +
            '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Importo</dt><dd>'  + button.parents('tr').find('.amount').html() + '</dd>' +
            '<dt>Data</dt><dd>'  + button.parents('tr').find('.date').html() + '</dd>' +
            '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });

    $(document).ready(function(){
        $('#my-table').DataTable({
            "columnDefs": [
                {"targets": 0, "type": 'date-eu'},      //data
                {"targets": 1, "type": 'currency-it'},  //importo
                {"orderable": false, "targets": -1}     //azioni
            ],
            "language":{
                "url": "/js/data-table-Italian.json"
            },
            "order": [
                [0, "desc"]
            ],
            "responsive": true,
            "searching": false
        });
    });

    $('#monthsFilterToggle').click(function () {
        if ($(this).find('i').hasClass('fa-chevron-down')) {
            $(this).find('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
            $('#collapseFilters').slideDown();
        } else {
            $(this).find('i').removeClass('fa-up').addClass('fa-chevron-down');
            $('#collapseFilters').slideUp();
        }
    });
    $('#remove-filters').click(function () {
        $('#collapseFilters input, #collapseFilters select').val('');
    });
</script>
<?php if ($rows): ?>
<?php $this->inlineScript()->captureStart(); ?>
Number.prototype.formatMoney = function(c, d, t){
    var n = this,
    c = isNaN(c = Math.abs(c)) ? 2 : c,
    d = d == undefined ? "." : d,
    t = t == undefined ? "," : t,
    s = n < 0 ? "-" : "",
    i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))),
    j = (j = i.length) > 3 ? j % 3 : 0;
    return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
};
Morris.Bar({
    barColors: ['#d9534f', '#5cb85c'],
    data: <?php echo json_encode($morrisData); ?>,
    element: 'morris',
    hideHover: "auto",
    labels: ['In uscita', 'In entrata'],
    xkey: 'x',
    ykeys: ['out', 'in'],
    resize: true,
    "xLabelFormat": function (x) {
        var d = x.label.split('-');
        return d[2] + '/' + d[1] + '/' + d[0];
    },
    "yLabelFormat": function (x) {
        return x.formatMoney(2, ',', '.') + ' €';
    }
});
Morris.Line({
    "dateFormat": function(unixTime) {
        var x = new Date(unixTime);
        var d = x.getDate();
        var m = x.getMonth() + 1;
        var y = x.getFullYear();
        return (d > 9 ? d : '0' + d) + '/' + (m > 9 ? m : '0' + m) + '/' + y;
    },
    "element": "balance-chart",
    "data": <?php echo json_encode($dataLineChart); ?>,
    "xkey": 'date',
    "ykeys": ['balance'],
    "labels": ['Saldo'],
    "resize": true,
    "xLabelFormat": function (x) {
        var d = x.getDate();
        var m = x.getMonth() + 1;
        var y = x.getFullYear();
        return (d > 9 ? d : '0' + d) + '/' + (m > 9 ? m : '0' + m) + '/' + y;
    },
    "yLabelFormat": function (x) {
        return x.formatMoney(2, ',', '.') + ' €';
    }
});
<?php $this->inlineScript()->captureEnd();?>
<?php endif;?>
<?php
$i = '<i class="mfb-component__child-icon glyphicon glyphicon-equalizer"></i>';
$this->floatingButtons()
    ->addAnchorItem(['href' => $this->url('accantonaMovement', ['action' => 'add', 'id' => $account->getId()], ['query' => $searchParams]), 'label' => 'Nuovo movimento', 'icon' => 'plus'])
    ->addAnchorItem(['href' => $this->url('accantonaMovement', ['action' => 'move', 'id' => $account->getId()], ['query' => $searchParams]), 'label' => 'Giroconto', 'icon' => 'transfer'])
    ->addRawItem("<span class=\"balance mfb-component__button--child\" data-toggle=\"modal\" data-target=\"#modal-balance\">$i</span>")
    ->addAnchorItem(['href' => $this->url('accantonaMovement', ['action' => 'export', 'id' => $account->getId()], ['query' => $searchParams]), 'label' => 'Esporta', 'icon' => 'export']);
