<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var MoneyLog\Form\MovementForm $form
 * @var array<string> $searchParams
 * @var int $accountId
 */
echo $this->pageHeader('Aggiungi movimento');
?>
<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Aggiungi movimento
            </div>
            <div class="panel-body">
                <?php echo $this->partial('money-log/movement/partials/movement', [
                    'accountId' => $accountId,
                    'form' => $form,
                    'searchParams' => $searchParams,
                ]); ?>
            </div>
        </div>
    </div>
</div>
