<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array<\Application\Entity\Movement> $rows
 */

echo implode(',', [
    '"Data"',
    '"Importo"',
    '"Descrizione"',
    '"Categoria"',
]) . PHP_EOL;

foreach ($rows as $row) {
    echo '"' . implode('","', [
        $this->dateForma($row->getDate()),
        number_format($row->getAmount(), 2, ',', ''),
        str_replace('"', '""', trim($row->getDescription())),
        $row->getCategory() ? str_replace('"', '""', $row->getCategory()->getDescrizione()) : '',
    ]) . '"' . PHP_EOL;
}
