<?php
/**
 * @var Doctrine\ORM\Tools\Pagination\Paginator<\Application\Entity\Movement> $paginator
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array<\Application\Entity\Account> $accounts
 * @var array<\Application\Entity\Category> $categories
 * @var array<array> $balances
 * @var array<string> $searchParams
 * @var int $page
 * @var int $totalPages
 */
?>
<style type="text/css">
    .has-error ul {
        color: #a94442;
        list-style-type: none;
        padding: 0;
    }
    #monthsFilter {
        margin: 8px 0;
    }
</style>
<?php echo $this->pageHeader('Movimenti'); ?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Saldi</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php foreach ($balances as $balance): ?>
                        <div class="col-lg-3"><strong><?php echo $balance['name']; ?>:</strong> <?php echo $this->currencyForma($balance['balance']); ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Saldi e filtri</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->synopsisFilters($searchParams, $categories); ?>
                        <a class="btn btn-default btn-circle pull-right" id="monthsFilterToggle"><i class="fa fa-chevron-down"></i></a>
                    </div>
                </div>
                <form class="collapse" id="collapseFilters">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label>Descrizione</label>
                                <input name="description" type="text" class="form-control" placeholder="Descrizione" value="<?php echo $searchParams['description']; ?>">
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3">
                            <div class="form-group">
                                <label>Conto</label>
                                <select class="form-control" name="account">
                                    <option value="0">Tutti</option>
                                    <?php foreach ($accounts as $account): ?>
                                        <option value="<?php echo $account->getId(); ?>"<?php if ($account->getId() == $searchParams['account']) echo ' selected="selected"'?>>
                                            <?php echo $account->getName(); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3">
                            <div class="form-group">
                                <label>Categoria</label>
                                <select class="form-control" name="category">
                                    <option value="0">Tutte</option>
                                    <?php foreach ($categories as $category): ?>
                                        <option value="<?php echo $category->getId(); ?>"<?php if ($category->getId() == $searchParams['category']) echo ' selected="selected"'?>>
                                            <?php echo $category->getDescription(); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Dal</label>
                                <input class="form-control" name="dateMin" type="date" value="<?php echo $searchParams['dateMin']; ?>"/>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Al</label>
                                <input class="form-control" name="dateMax" type="date" value="<?php echo $searchParams['dateMax']; ?>"/>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Importo minimo</label>
                                <input class="form-control" name="amountMin" type="number" step="0.01" value="<?php echo $searchParams['amountMin']; ?>"/>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="form-group">
                                <label>Impoto massimo</label>
                                <input class="form-control" name="amountMax" type="number" step="0.01" value="<?php echo $searchParams['amountMax']; ?>"/>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <button type="button" class="form-control btn btn-danger" value="Azzera" id="remove-filters"><i class="fa fa-remove"></i> Rimuovi filtri</button>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary" value="cerca"><i class="fa fa-search"></i> Cerca</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Lista movimenti</div>
                <table class="table table-striped table-bordered table-hover responsive">
                    <thead>
                        <tr>
                            <th>Data</th>
                            <th>Conto</th>
                            <th>Importo</th>
                            <th>Descrizione</th>
                            <th>Categoria</th>
                            <th style="width: 69px;">Azioni</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($paginator as $row): ?>
                        <tr>
                            <td class="date"><?php echo $this->dateForma($row->getDate()); ?></td>
                            <td class="account"><?php echo $row->getAccount()->getName(); ?></td>
                            <td class="text-right amount"><?php echo $this->currencyForma($row->getAmount()); ?></td>
                            <td class="description"><?php echo $row->getDescription(); ?></td>
                            <td class="description"><?php echo null !== ($c = $row->getCategory()) ? $c->getDescription() : ''; ?></td>
                            <td class="text-right">
                                <a href="<?php echo $this->url('accantonaMovement', ['action' => 'edit', 'id' => $row->getId()], ['query' => $searchParams]); ?>" class="btn btn-default btn-xs" title="Modifica">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <span data-href="<?php echo $this->url('accantonaMovement', ['action' => 'delete', 'id' => $row->getId()], ['query' => $searchParams]); ?>" class="btn btn-default btn-xs delete-item" title="Elimina">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </span>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="text-center">
            <?php echo $this->pagination($paginator, $page, 'accantonaMovement', $searchParams); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).on("click", ".delete-item", function(e) {
        var button = $(this);

        var html = '<h3>Cancellare il movimento selezionato?</h3>' +
            '<dl class="dl-horizontal">' +
            '<dt>Descrizione</dt><dd>'  + button.parents('tr').find('.description').html() + '</dd>' +
            '<dt>Importo</dt><dd>'  + button.parents('tr').find('.amount').html() + '</dd>' +
            '<dt>Data</dt><dd>'  + button.parents('tr').find('.date').html() + '</dd>' +
            '</dl>';
        bootbox.confirm(html, function(result) {
            if (result) {
                location.href =  button.data('href');
            }
        });
    });

    $('#monthsFilterToggle').click(function () {
        if ($(this).find('i').hasClass('fa-chevron-down')) {
            $(this).find('i').removeClass('fa-chevron-down').addClass('fa-chevron-up');
            $('#collapseFilters').slideDown();
        } else {
            $(this).find('i').removeClass('fa-up').addClass('fa-chevron-down');
            $('#collapseFilters').slideUp();
        }
    });
    $('#remove-filters').click(function () {
        $('#collapseFilters input, #collapseFilters select').val('');
    });
</script>
<?php
$i = '<i class="mfb-component__child-icon glyphicon glyphicon-equalizer"></i>';
$this->floatingButtons()
    ->addAnchorItem(['href' => $this->url('accantonaMovement', ['action' => 'add'], ['query' => $searchParams]), 'label' => 'Nuovo movimento', 'icon' => 'plus'])
    ->addAnchorItem(['href' => $this->url('accantonaMovement', ['action' => 'move'], ['query' => $searchParams]), 'label' => 'Giroconto', 'icon' => 'transfer'])
    ->addRawItem("<span class=\"balance mfb-component__button--child\" data-toggle=\"modal\" data-target=\"#modal-balance\">$i</span>")
    ->addAnchorItem(['href' => $this->url('accantonaMovement', ['action' => 'export'], ['query' => $searchParams]), 'label' => 'Esporta', 'icon' => 'export']);
