<?php
/** @var $form \Zend\Form\Form */
echo $this->pageHeader('Giroconto');
?>
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">Preleva da <?php echo $this->sourceAccount->name; ?></div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($this->form); ?>

                    <?php echo $this->sbaFormRow($form->get('date')); ?>
                    <?php echo $this->sbaFormRow($form->get('amount')); ?>
                    <?php echo $this->sbaFormRow($form->get('description')); ?>
                    <?php echo $this->sbaFormRow($form->get('targetAccountId')); ?>

                    <div class="text-right">
                        <a class="btn btn-default" href="<?php echo $this->url('accantonaMovement', ['action' => 'account', 'id' => $this->sourceAccount->id], ['query' => $searchParams]) ?>">
                            Annulla
                        </a>
                        <button type="submit" class="btn btn-primary">Sposta</button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4"></div>
</div>
