<?php
/**
 * @var \Application\Entity\Account $sourceAccount
 * @var \Laminas\Form\Form $form
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
echo $this->pageHeader('Giroconto');
?>
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">Preleva da <?php echo $sourceAccount->getName(); ?></div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>

                    <?php echo $this->sbaFormRow($form->get('date')); ?>
                    <?php echo $this->sbaFormRow($form->get('amount')); ?>
                    <?php echo $this->sbaFormRow($form->get('description')); ?>
                    <?php echo $this->sbaFormRow($form->get('targetAccountId')); ?>

                    <div class="text-right">
                        <a class="btn btn-default" href="<?php echo $this->url('accantonaAccount') ?>">Annulla</a>
                        <button type="submit" class="btn btn-primary">Sposta</button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4"></div>
</div>
