<?php echo $this->pageHeader('Aggiungi entrata'); ?>
<div class="row">
    <div class="col-lg-4">
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Aggiungi entrata in <?php echo $sourceAccount->name; ?>
            </div>
            <div class="panel-body">
                <?php echo $this->partial('accantona/movement/partials/movement'); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
    </div>
</div>
