<style type="text/css">
    .form-setting {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
</style>
<form class="form-setting" action="<?php echo $this->url(); ?>">
    <div class="row form-group">
        <h1>Impostazioni</h1>
    </div>
    <?php foreach ($userSettings as $setting): ?>
    <div class="row form-group">
        <?php echo $this->formLabel($settingForm->get('payDay')); ?>
        <?php echo $this->formInput($settingForm->get('payDay')); ?>
        </div>
    <?php endforeach; ?>
    <div class="row form-group">
        <input class="form-control btn-primary" type="submit" value="Salva" />
    </div>
</form>