<style type="text/css">
    .form-setting {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
</style>
<?php echo $this->pageHeader($title); ?>
<form class="form-setting" method="post" action="<?php echo $this->url(); ?>">

    <?php if ($message): ?>
        <div class="row alert alert-success" role="alert"><?php echo $message; ?></div>
    <?php endif; ?>

    <?php $element = $form->get('payDay'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="row form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <div class="row form-group">
        <input class="form-control btn-primary" type="submit" value="Salva" />
    </div>
</form>