<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var MoneyLog\Form\ProvisionForm $form
 * @var array<string> $searchParams
 * @var string $id
 */
echo $this->pageHeader('Modifica accantonamento');
?>
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel panel-heading">Modifica accantonamento</div>
            <div class="panel panel-body">
                <?php $form->setAttribute('action', $this->url('accantona_accantonato', ['action' => 'edit', 'id' => $id], ['query' => $searchParams])); ?>
                <?php $form->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>

                    <?php echo $this->sbaFormRow($form->get('date')); ?>
                    <?php echo $this->sbaFormRow($form->get('amount')); ?>
                    <?php echo $this->sbaFormRow($form->get('description')); ?>

                    <div class="text-right">
                        <a class="btn btn-default" href="<?php echo $this->url('accantona_accantonato', ['action' => 'index'], ['query' => $searchParams]) ?>">Annulla</a>
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> Salva</button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4"></div>
</div>
