<?php
$title = 'Aggiungi categoria';
$this->headTitle($title);
$form->setAttribute('action', $this->url('accantona_categoria', array('action' => 'add')));
$form->prepare();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>

    <?php echo $this->formHidden($form->get('id')); ?>

    <?php $element = $form->get('descrizione'); ?>
    <?php $errors = $this->formElementErrors($element); ?>
    <div class="form-group <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $errors; ?>
    </div>

    <?php
    $element = $form->get('status');
    $element->setLabelAttributes(array('for' => 'categotyStatus'));
    $errors = $this->formElementErrors($element);
    ?>
    <div class="checkbox <?php if ($errors) echo 'has-error'; ?>">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formCheckbox($element); ?>
        <?php echo $errors; ?>
    </div>

    <div class="text-right">
        <button id="save" type="submit" class="btn btn-default show-on-edit" aria-label="Salva">
            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Salva
        </button>
    </div>

<?php echo $this->form()->closeTag(); ?>
