<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 $title = 'Delete category';
 $this->headTitle($title);
 ?>
<div class="row">
    <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
</div>
 <p>
     Are you sure that you want to delete '<?php echo $this->escapeHtml($category->descrizione); ?>'?
 </p>
 <?php
 $url = $this->url('accantona_categoria', array('action' => 'delete', 'id' => $this->id));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $category->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>
