<?php
$title = 'Edit category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$this->form->setAttribute('action', $this->url('accantona_categoria', array('action' => 'edit', 'id' => $this->id)));
$this->form->prepare();

echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('id'));
?>
<div class="row">
    <label>
        <?php echo $this->form->get('descrizione')->getLabel(); ?>
        <input class="form-control" type="text" name="descrizione" value="<?php echo $this->form->get('descrizione')->getValue(); ?>">
    </label>
</div>
<div class="row">
    <button id="save" type="submit" class="btn btn-default show-on-edit" aria-label="Salva">
        <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Salva
    </button>
</div>
<?php echo $this->form()->closeTag(); ?>
