<?php
$title = 'Categorie di spesa';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
    <tr>
        <th>Descrizione</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($rows as $row) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($row->descrizione); ?></td>
        <td class="text-right">
            <a href="<?php echo $this->url('accantona_categoria', array('action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-default" aria-label="Edit">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </a>
            <a href="<?php echo $this->url('accantona_categoria', array('action' => 'delete', 'id' => $row->id)); ?>" class="btn btn-default" aria-label="Edit">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
    <tfoot>
        <tr>
            <td class="text-right" colspan="3">
                <a href="<?php echo $this->url('accantona_categoria', array('action' => 'add')); ?>" class="btn btn-default" aria-label="Add">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
                </a>
            </td>
        </tr>
    </tfoot>
</table>